services:
  watchtower:
    image: containrrr/watchtower:latest
    container_name: watchtower
    hostname: watchtower
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      TZ: "Europe/Rome"
      WATCHTOWER_LABEL_ENABLE: "true"
      WATCHTOWER_SCHEDULE: "0 */3 * * * *"
      WATCHTOWER_CLEANUP: "true"
      WATCHTOWER_TIMEOUT: "60s"
      WATCHTOWER_NOTIFICATIONS: "gotify"
      WATCHTOWER_NOTIFICATION_GOTIFY_URL: "https://gotify.esp32.ip-ddns.com/"
      WATCHTOWER_NOTIFICATION_GOTIFY_TOKEN: "AA41dkN91IOyZOo"