version: '3.8'

volumes:
  evolution_api_data:
    name: evolution_api_data
    driver: local
  mongodb_whatsapp_data:
    name: mongodb_whatsapp_data
    driver: local

networks:
  whatsapp-net:
    driver: bridge
  reverse-proxy:
    external: true

services:
  evolution-api:
    image: atende/evolution-api:latest
    container_name: evolution-api
    hostname: evolution-api
    restart: unless-stopped
    volumes:
      - evolution_api_data:/evolution/store
    networks:
      - whatsapp-net
      - reverse-proxy
    env_file:
      - .env
    depends_on:
      - mongodb-whatsapp

  mongodb-whatsapp:
    image: mongo:latest
    container_name: mongodb-whatsapp
    hostname: mongodb-whatsapp
    restart: unless-stopped
    volumes:
      - mongodb_whatsapp_data:/data/db
    networks:
      - whatsapp-net